osx_image: xcode11.3
language: node_js

env:
  global:
    - FORCE_COLOR=1

matrix:
  include:
    - os: osx
      env: TEST_FILES=BuildTest,extraMetadataTest,globTest,filesTest,ignoreTest,linux,windows,macIconTest
      node_js: "12"

    - os: osx
      env: TEST_FILES=CodeSignTest,macArchiveTest,macPackagerTest
      node_js: "12"

    - os: osx
      env: TEST_FILES=masTest,dmgTest,protonTest
      node_js: "12"

cache:
  yarn: true
  directories:
    - .yarn
    - $HOME/Library/Caches/electron
    - $HOME/Library/Caches/electron-builder
    - /tmp/jest-electron-builder-tests

install:
  - node .yarn/releases/yarn-sources.js

script:
  - node .yarn/releases/yarn-sources.js test

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"