image: Visual Studio 2019
platform: x64

cache:
  - .yarn
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

environment:
  TEST_FILES: ExtraBuildTest,BuildTest,extraMetadataTest,filesTest,globTest,nsisUpdaterTest,oneClickInstallerTest,installerTest,appxTest,msiTest,protonTest

install:
  - ps: Install-Product node 12 x64
  - YARN_CHECKSUM_BEHAVIOR=ignore node .yarn/releases/yarn-sources.js install

build: off

test_script:
  - node .yarn/releases/yarn-sources.js test